const CharactersActionTypes = {
    FETCH_CHARACTERS_START: 'FETCH_CHARACTERS_START',
    FETCH_CHARACTERS_SUCCESS: 'FETCH_CHARACTERS_SUCCESS',
    FETCH_CHARACTERS_FAILURE: 'FETCH_CHARACTERS_FAILURE',
  };
  
export default CharactersActionTypes;